[projects."/home/hyper/tmp"]
trust_level = "trusted"

[projects."/home/hyper/tmp/dotfiles"]
trust_level = "trusted"

[projects."/home/hyper"]
trust_level = "trusted"

[projects."/home/hyper/proj/sophion/docs"]
trust_level = "trusted"

[tui]
status_line = ["model-with-reasoning", "current-dir", "context-usage", "five-hour-limit", "weekly-limit", "used-tokens"]
