#################
### AUTOSTART ###
#################

exec-once = waybar &
exec-once = awww-daemon &
exec-once = nm-applet &
exec-once = fcitx5 &
exec-once = blueman-applet &
exec-once = swaync &
exec-once = discord &
exec-once = slack &
exec-once = systemctl --user start hyprpolkitagent
exec-once = hyprctl setcursor Bibata-Modern-Ice 24
