#################
### AUTOSTART ###
#################

# Core desktop components
exec-once = waybar
exec-once = awww-daemon
exec-once = nm-applet
exec-once = fcitx5
exec-once = blueman-applet
exec-once = swaync
exec-once = hyprctl setcursor Bibata-Modern-Ice 24

# Idle / background services
exec-once = hypridle

# Heavier apps: start them a bit later to avoid slowing down session startup
exec-once = sleep 2 && discord
exec-once = sleep 3 && slack
