###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

$mainMod = SUPER
$terminal = kitty
$fileManager = nautilus
$editor = zeditor
$browser = zen-browser
$launcher = rofi -show drun
$windowSwitcher = rofi -show window
$lockCmd = hyprlock


#################
### AUTOSTART ###
#################

exec-once = waybar &
exec-once = awww-daemon &
exec-once = nm-applet &
exec-once = fcitx5 &
exec-once = blueman-applet &
exec-once = swaync
exec-once = discord
exec-once = systemctl --user start hyprpolkitagent


#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hypr.land/Configuring/Environment-variables/

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

env = NIXOS_OZONE_WL,1
env = ELECTRON_OZONE_PLATFORM_HINT,wayland

misc {
    force_default_wallpaper = -1
    disable_hyprland_logo = false
}


#############
### INPUT ###
#############

input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options = caps:escape
    kb_rules =

    follow_mouse = 1
    sensitivity = 0

    touchpad {
        natural_scroll = true
        disable_while_typing = true
    }
}

gesture = 3, horizontal, workspace
