###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

$mainMod = SUPER
$terminal = kitty
$fileManager = nautilus
$editor = zeditor
$browser = zen-browser
$launcher = rofi -show drun
$windowSwitcher = rofi -show window
$lockCmd = hyprlock


#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hypr.land/Configuring/Environment-variables/

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = HYPRCURSOR_THEME,Bibata-Modern-Ice

env = NIXOS_OZONE_WL,1
env = ELECTRON_OZONE_PLATFORM_HINT,wayland

env = QT_QPA_PLATFORM,wayland
env = QT_QPA_PLATFORMTHEME,qt5ct
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_STYLE_OVERRIDE,quantum

#############
### INPUT ###
#############

input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options = caps:escape
    kb_rules =

    follow_mouse = 1
    sensitivity = 0

    touchpad {
        natural_scroll = true
        disable_while_typing = true
    }
}

gesture = 3, horizontal, workspace
