##############################
### WINDOWS AND WORKSPACES ###
##############################

windowrule {
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# windowrule {
#     name = move-hyprland-run
#     match:class = hyprland-run

#     move = 20 monitor_h-120
#     float = yes
# }

windowrule {
    name = center-float-pavucontrol
    match:class = (?i).*pavucontrol.*

    float = on
    center = on
    size = (monitor_w*0.5) (monitor_h*0.8)
}

misc {
    on_focus_under_fullscreen = 1
}

# discord to secret workspace D
windowrule {
    name = move-discord-to-scratchpad
    match:class = ^(?i)discord$

    # Move Discord to special workspace "qaq" without switching to it
    workspace = special:qaq silent
}

# slack to secret workspace S
windowrule {
    name = move-slack-to-scratchpad
    match:class = ^(?i)slack$

    workspace = special:owo silent
}
